import { ProjectWithRelations, ProjectResearchArea, ProjectResearcher, ProjectCollaborator, ProjectPublication } from "./types";

export const SEED_RESEARCH_AREAS: ProjectResearchArea[] = [
  {
    id: "area-1",
    title: "Microplastics & Emerging Pollutants",
    slug: "microplastics-emerging-pollutants",
    description: "Polymer characterization, particulate transport kinetics, and trophic transfer in freshwater and coastal ecosystems.",
    icon_name: "FlaskConical",
  },
  {
    id: "area-2",
    title: "Heavy Metal Ecotoxicology",
    slug: "heavy-metal-ecotoxicology",
    description: "Speciation, bioaccumulation, and cellular biomarkers of arsenic, lead, cadmium, and chromium across agro-ecosystems.",
    icon_name: "Atom",
  },
  {
    id: "area-3",
    title: "Aquatic Health & Watersheds",
    slug: "aquatic-health-watersheds",
    description: "Longitudinal river basin water quality, industrial discharge monitoring, and benthic macroinvertebrate health.",
    icon_name: "Droplets",
  },
  {
    id: "area-4",
    title: "Human Health Risk Assessment",
    slug: "human-health-risk-assessment",
    description: "Dietary exposure pathways, daily intake estimations, and non-carcinogenic/carcinogenic hazard quotients.",
    icon_name: "Activity",
  },
  {
    id: "area-5",
    title: "Environmental Remediation Technologies",
    slug: "environmental-remediation-technologies",
    description: "Engineered biochar composites, phytoremediation matrices, and sustainable industrial effluent treatment systems.",
    icon_name: "Leaf",
  },
];

export const SEED_RESEARCHERS: ProjectResearcher[] = [
  {
    id: "person-1",
    name: "Dr. Elena Vance",
    slug: "dr-elena-vance",
    position: "Principal Investigator & Lab Director",
    photo_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
    role_in_project: "Principal Investigator",
    display_order: 1,
  },
  {
    id: "person-2",
    name: "Sojib Chowdhury",
    slug: "sojib-chowdhury",
    position: "Senior Research Fellow & Analytical Lead",
    photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    role_in_project: "Lead Field & Analytical Researcher",
    display_order: 2,
  },
  {
    id: "person-3",
    name: "Dr. Marcus Thorne",
    slug: "dr-marcus-thorne",
    position: "Senior Ecotoxicologist",
    photo_url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=600&q=80",
    role_in_project: "Co-Investigator",
    display_order: 3,
  },
  {
    id: "person-4",
    name: "Aria Lindqvist",
    slug: "aria-lindqvist",
    position: "Graduate Research Assistant",
    photo_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
    role_in_project: "Spectroscopy & Data Specialist",
    display_order: 4,
  },
  {
    id: "person-5",
    name: "Tanvir Hasan",
    slug: "tanvir-hasan",
    position: "Graduate Fellow",
    photo_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
    role_in_project: "Field Sampling Coordinator",
    display_order: 5,
  },
  {
    id: "person-6",
    name: "Kotoha Nakayama",
    slug: "kotoha-nakayama",
    position: "Postdoctoral Research Fellow",
    photo_url: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=600&q=80",
    role_in_project: "Molecular Ecotoxicology & Bioassay Lead",
    display_order: 6,
  },
];

export const SEED_COLLABORATORS: ProjectCollaborator[] = [
  {
    name: "Jahangirnagar University",
    institution: "Dept. of Environmental Sciences",
    role: "Host Academic Institution",
  },
  {
    name: "Ministry of Science & Technology (MoST)",
    institution: "Government of Bangladesh",
    role: "National Research Funding Partner",
  },
  {
    name: "Department of Environment (DoE)",
    institution: "Ministry of Environment, Forest & Climate Change",
    role: "Regulatory & Monitoring Partner",
  },
  {
    name: "U.S. EPA Office of Research",
    institution: "United States Environmental Protection Agency",
    role: "International Scientific Collaborator",
  },
];

export const SEED_PROJECTS: ProjectWithRelations[] = [
  {
    id: "proj-001",
    title: "Microplastic Exposure in Freshwater Ecosystems: Trophic Transfer & Biomagnification",
    slug: "microplastic-exposure-freshwater-ecosystems",
    short_description: "Longitudinal multi-station investigation into particulate microplastic abundance, polymeric composition, and trophic biomagnification in the Meghna River estuary.",
    full_description: "Micro- and nanoplastics represent an escalating ecotoxicological crisis in rapidly industrializing deltaic river systems. This flagship 3-year research initiative systematically quantifies polymer distribution (polyethylene, polypropylene, polystyrene) across benthic sediment cores, surface water microlayers, and commercial fish species in the Meghna River basin.\n\nBy integrating micro-FTIR imaging with digestion-free fluorescent tagging, the project determines the bioaccumulation factors and histological alterations in local fish models (Tenualosa ilisha, Glossogobius giuris), establishing critical baseline contamination metrics for South Asian delta environments.",
    status: "ongoing",
    start_date: "2025-01-15",
    end_date: "2027-12-31",
    year: "2025 — 2027",
    funding_info: "Competitive National Science & Technology Research Grant #MoST-ENV-2024-88",
    funding_org: "Ministry of Science & Technology (MoST)",
    grant_amount: "BDT 3.6M ($32,000 USD)",
    research_question: "How do seasonal hydrodynamic shifts govern the fragmentation, bio-uptake, and trophic magnification of microplastics across freshwater-estuarine food webs?",
    objectives: [
      "Quantify temporal and spatial concentrations of microplastics in surface water and sediment across 18 sampling stations.",
      "Characterize polymer fingerprints and chemical additives using micro-FTIR and thermal desorption GC-MS.",
      "Assess cellular oxidative stress and gastrointestinal lesion severity in commercially harvested fish species.",
      "Formulate a localized ecological risk index (ERI) to inform national plastics abatement regulations."
    ],
    methodology: "Standardized NOAA manta trawl surface sampling → Alkaline KOH tissue digestion → μ-FTIR spectral mapping (4000–600 cm⁻¹) → Biomarker enzyme assays (CAT, SOD, MDA) → Multivariable Bayesian spatial modeling.",
    study_area: "Meghna River Estuary & Coastal Outfall Transects",
    study_area_description: "Covering 120 km of river corridor stretching from Chandpur confluence to Bhola coastal outlet, capturing diverse industrial, urban, and agricultural discharge zones.",
    findings: "Initial preliminary data reveals elevated concentrations (up to 480 particles/m³) during the pre-monsoon dry season, dominated by polypropylene fibers and weathered fragments.",
    outputs: "3 Peer-reviewed Journal Articles (in prep), 1 Open-Access Spectral Library, National Environmental Policy Brief #04.",
    hero_image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1600&q=85",
    image_alt: "Laboratory researcher examining microplastic particles under automated optical microscope",
    featured_image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "/images/gallery/field-sampling.jpg",
      "/images/gallery/microscopy-imaging.jpg"
    ],
    display_order: 1,
    is_featured: true,
    is_published: true,
    published_at: "2025-01-15T00:00:00Z",
    created_at: "2025-01-15T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
    research_areas: [SEED_RESEARCH_AREAS[0], SEED_RESEARCH_AREAS[2]],
    researchers: [SEED_RESEARCHERS[0], SEED_RESEARCHERS[1], SEED_RESEARCHERS[3]],
    collaborators: [SEED_COLLABORATORS[0], SEED_COLLABORATORS[1]],
    publications: [
      {
        id: "pub-1",
        title: "Microplastic Polymer Fingerprints in Estuarine Bioindicators: Seasonal Dynamics and Biomagnification",
        slug: "microplastic-polymer-fingerprints-estuarine-bioindicators",
        journal: "Science of The Total Environment",
        publication_year: 2025,
        doi: "10.1016/j.scitotenv.2025.178234",
        authors: "Chowdhury, S., Vance, E., Thorne, M., Lindqvist, A.",
      }
    ]
  },
  {
    id: "proj-002",
    title: "Heavy Metal Speciation & Dietary Health Risk in Peri-Urban Agro-Ecosystems",
    slug: "heavy-metal-speciation-agro-ecosystems",
    short_description: "Spatial mapping of trace elements (Pb, Cd, As, Cr) in the soil-water-crop continuum and human health risk quotient modeling in the Gazipur-Savar industrial belt.",
    full_description: "Industrial effluents and untreated wastewater irrigation in peri-urban agricultural corridors introduce hazardous concentrations of toxic trace elements into the human food chain. This study examines the fractionation of arsenic, cadmium, lead, and chromium in agricultural soils, irrigational canals, and leafy vegetables.\n\nEmploying inductively coupled plasma mass spectrometry (ICP-MS) and sequential extraction procedures (BCR), the project calculates bioconcentration factors (BCF), target hazard quotients (THQ), and incremental lifetime cancer risk (ILCR) for local consumer populations.",
    status: "ongoing",
    start_date: "2024-06-01",
    end_date: "2026-11-30",
    year: "2024 — 2026",
    funding_info: "Higher Education Quality Enhancement Project (HEQEP) Research Grant #W2-892",
    funding_org: "World Bank & UGC Bangladesh",
    grant_amount: "BDT 4.8M ($41,000 USD)",
    research_question: "To what extent does chemical speciation control heavy metal bioavailability in wastewater-irrigated soils, and what are the resulting dietary exposure hazards?",
    objectives: [
      "Profile total and bioavailable heavy metals in soil, irrigation water, and 12 vegetable cultivars.",
      "Conduct sequential extraction to evaluate geochemical fractionation (exchangeable, reducible, oxidizable, residual).",
      "Model adult and child Target Hazard Quotients (THQ) based on localized dietary surveys.",
      "Deliver actionable spatial zoning maps to agricultural extension officers."
    ],
    methodology: "Soil core sampling (0–20 cm) → Microwave acid digestion (EPA 3051A) → ICP-MS trace metal quantification → BCR sequential extraction → USEPA Monte Carlo health risk simulation.",
    study_area: "Gazipur-Savar Peri-Urban Agricultural Zone",
    study_area_description: "High-density textile and tannery catchment areas bordering Dhaka city, characterized by intensive vegetable cultivation and canal irrigation.",
    findings: "Cadmium and Lead bioaccumulation in spinach and amaranth species consistently exceeded FAO/WHO codex maximum permissible levels during dry irrigation cycles.",
    outputs: "2 Peer-Reviewed Papers, 1 GIS Soil Risk Atlas, Policy Recommendations for Wastewater Irrigation Zoning.",
    hero_image: "/images/slide-1-field.jpg",
    image_alt: "Soil and water sample collection in agricultural wetland monitoring site",
    featured_image: "/images/slide-1-field.jpg",
    gallery: [
      "/images/gallery/field-sampling.jpg"
    ],
    display_order: 2,
    is_featured: true,
    is_published: true,
    published_at: "2024-06-01T00:00:00Z",
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
    research_areas: [SEED_RESEARCH_AREAS[1], SEED_RESEARCH_AREAS[3]],
    researchers: [SEED_RESEARCHERS[0], SEED_RESEARCHERS[2], SEED_RESEARCHERS[4]],
    collaborators: [SEED_COLLABORATORS[0], SEED_COLLABORATORS[2]],
    publications: []
  },
  {
    id: "proj-003",
    title: "Engineered Biochar Composites for Low-Cost Industrial Effluent Remediation",
    slug: "engineered-biochar-effluent-remediation",
    short_description: "Development and synthesis of pyrolyzed agricultural biomass composites tailored for simultaneous adsorption of synthetic azo dyes and toxic metal ions.",
    full_description: "Industrial wastewater treatment in resource-constrained environments necessitates cost-effective, high-capacity adsorbent materials. This project developed magnetic iron oxide-modified biochar derived from agricultural waste (rice husk and sugarcane bagasse).\n\nThrough batch equilibrium experiments, continuous column studies, and surface characterization (BET, XPS, SEM-EDX), the team optimized sorption isotherms and dynamic column breakthrough curves, demonstrating >96% removal efficiency for reactive azo dyes and toxic divalent cations.",
    status: "completed",
    start_date: "2023-01-10",
    end_date: "2025-06-30",
    year: "2023 — 2025",
    funding_info: "University Grants Commission Research Support Fund #UGC-EST-23",
    funding_org: "University Grants Commission (UGC)",
    grant_amount: "BDT 2.1M ($18,000 USD)",
    research_question: "Can surface-functionalized agricultural biochars achieve high-throughput multi-pollutant capture in high-salinity textile wastewater?",
    objectives: [
      "Synthesize magnetized agricultural biochar pyrolyzed at 450°C and 700°C.",
      "Quantify Langmuir and Freundlich adsorption isotherms for Reactive Black 5 and Methylene Blue.",
      "Evaluate reusability across 6 regeneration and desorption cycles.",
      "Design a continuous packed-bed pilot filtration prototype."
    ],
    methodology: "Biomass slow pyrolysis → Chemical co-precipitation of Fe3O4 → BET surface area porosity analysis → Batch kinetic studies → Breakthrough column modeling.",
    study_area: "Ecotoxicology Laboratory & Tannery Effluent Discharge Outfalls",
    study_area_description: "Laboratory-scale synthesis and real effluent testing from Hazaribagh-Hemayetpur industrial wastewater conduits.",
    findings: "The magnetized biochar composite achieved maximum sorption capacities of 184 mg/g for dyes and 68 mg/g for Cr(VI), maintaining >88% efficiency over 5 regenerations.",
    outputs: "4 Published Journal Articles, 1 Utility Patent Application (Pending), 1 Pilot Filter Unit Prototype.",
    hero_image: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=1600&q=85",
    image_alt: "Continuous flow bioremediation column and biochar filtration testing system",
    featured_image: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=1600&q=85",
    gallery: [
      "https://images.unsplash.com/photo-1582719471384-894fbb16e074?auto=format&fit=crop&w=1200&q=80"
    ],
    display_order: 3,
    is_featured: false,
    is_published: true,
    published_at: "2023-01-10T00:00:00Z",
    created_at: "2023-01-10T00:00:00Z",
    updated_at: "2025-07-01T00:00:00Z",
    research_areas: [SEED_RESEARCH_AREAS[4]],
    researchers: [SEED_RESEARCHERS[1], SEED_RESEARCHERS[3]],
    collaborators: [SEED_COLLABORATORS[0]],
    publications: []
  },
  {
    id: "proj-004",
    title: "Pesticide Leaching Dynamics & Groundwater Vulnerability Modeling in Intensive Agriculture",
    slug: "pesticide-leaching-groundwater-vulnerability",
    short_description: "High-resolution screening of organophosphates and neonicotinoids across intensive agricultural soils to model shallow aquifer vulnerability.",
    full_description: "Intensive horticultural production relies heavily on multiple pesticide applications, raising concerns over groundwater contamination in shallow unconfined aquifers. This project monitored pesticide leaching kinetics across sandy-loam vadose zones in the Bogura-Rajshahi agricultural belt.\n\nUtilizing solid-phase extraction (SPE) and high-performance liquid chromatography tandem mass spectrometry (HPLC-MS/MS), groundwater vulnerability indices (DRASTIC and Leaching Potential Index) were calculated for the northern floodplains.",
    status: "completed",
    start_date: "2022-03-01",
    end_date: "2024-12-31",
    year: "2022 — 2024",
    funding_info: "National Science Research Program #NSRP-2022",
    funding_org: "Ministry of Science & Technology",
    grant_amount: "BDT 1.9M ($16,500 USD)",
    research_question: "What hydrogeological factors govern the preferential macropore flow and deep aquifer breakthrough of neonicotinoids under monsoonal infiltration?",
    objectives: [
      "Collect and analyze 240 groundwater tubewell samples across wet and dry seasons.",
      "Quantify 16 target pesticide active ingredients and primary metabolites.",
      "Develop GIS-coupled DRASTIC groundwater vulnerability maps.",
      "Provide pesticide safety workshops for regional farmer cooperatives."
    ],
    methodology: "Vadose zone suction lysimeter sampling → SPE Cartridge clean-up → HPLC-MS/MS quantification → Hydrogeological GIS matrix modeling.",
    study_area: "Northern Floodplain Horticultural Belt (Bogura & Rajshahi)",
    study_area_description: "Intensive triple-cropped vegetable producing districts relying exclusively on shallow tubewells for domestic and irrigation use.",
    findings: "Chlorpyrifos and imidacloprid detected in 34% of monitored shallow tubewells, correlating strongly with sandy vadose texture and post-monsoon infiltration events.",
    outputs: "3 Peer-reviewed Publications, Regional Vulnerability GIS Dataset, 4 Community Farmer Training Seminars.",
    hero_image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1600&q=85",
    image_alt: "Agricultural floodplain fields with hydrological sampling instrumentation",
    featured_image: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    display_order: 4,
    is_featured: false,
    is_published: true,
    published_at: "2022-03-01T00:00:00Z",
    created_at: "2022-03-01T00:00:00Z",
    updated_at: "2025-01-10T00:00:00Z",
    research_areas: [SEED_RESEARCH_AREAS[2], SEED_RESEARCH_AREAS[3]],
    researchers: [SEED_RESEARCHERS[0], SEED_RESEARCHERS[4]],
    collaborators: [SEED_COLLABORATORS[0], SEED_COLLABORATORS[2]],
    publications: []
  },
  {
    id: "proj-005",
    title: "PFAS Bioaccumulation & Hepatic Biomarkers in Estuarine Finfish",
    slug: "pfas-bioaccumulation-estuarine-finfish",
    short_description: "Assessing per- and polyfluoroalkyl substances (PFAS) contamination pathways and cellular toxicological biomarkers in coastal fishery resources.",
    full_description: "Per- and polyfluoroalkyl substances ('forever chemicals') accumulate in high concentrations along coastal industrial discharge zones. This targeted research investigation assesses PFOA and PFOS burdens in liver, muscle, and gill tissues of commercially important estuarine finfish species.\n\nBiochemical assays evaluate lipid peroxidation, catalase suppression, and ethoxyresorufin-O-deethylase (EROD) induction to link chemical body burdens with physiological distress.",
    status: "ongoing",
    start_date: "2025-03-01",
    end_date: "2027-08-31",
    year: "2025 — 2027",
    funding_info: "International Collaborative Ecotoxicology Fund #ICEF-25",
    funding_org: "U.S. EPA Office of Research & MoST",
    grant_amount: "BDT 5.2M ($44,000 USD)",
    research_question: "Which PFAS congeners exhibit the highest bioaccumulation factors in tropical estuarine food webs, and what are the cellular toxicity thresholds?",
    objectives: [
      "Analyze 24 PFAS congeners in coastal water, sediment, and 8 fish taxa.",
      "Evaluate hepatic enzyme alterations and histopathological damage in liver tissue.",
      "Determine human dietary intake and benchmark dose hazard rates."
    ],
    methodology: "Tissue homogenization → Weak anion exchange (WAX) SPE → LC-HRMS Orbitrap detection → Spectrophotometric biomarker profiling.",
    study_area: "Karnafuli River Estuary & Chittagong Coastal Zone",
    study_area_description: "Major shipping and industrial port corridor receiving municipal and industrial discharges.",
    findings: "Targeted testing confirms PFOS presence in 82% of apex predatory estuarine samples, with highest concentration in liver homogenates.",
    outputs: "Initial baseline survey dataset, 1 International Conference Paper.",
    hero_image: "https://images.unsplash.com/photo-1544377193-33dcf4d68fb5?auto=format&fit=crop&w=1600&q=85",
    image_alt: "Estuarine sampling vessel and water quality monitoring sensor deployment",
    featured_image: "https://images.unsplash.com/photo-1544377193-33dcf4d68fb5?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    display_order: 5,
    is_featured: false,
    is_published: true,
    published_at: "2025-03-01T00:00:00Z",
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2026-03-05T00:00:00Z",
    research_areas: [SEED_RESEARCH_AREAS[0], SEED_RESEARCH_AREAS[1]],
    researchers: [SEED_RESEARCHERS[0], SEED_RESEARCHERS[1], SEED_RESEARCHERS[2]],
    collaborators: [SEED_COLLABORATORS[0], SEED_COLLABORATORS[3]],
    publications: []
  },
  {
    id: "proj-006",
    title: "Atmospheric Particulate Heavy Metal Deposition & Urban Biomonitoring",
    slug: "atmospheric-heavy-metal-biomonitoring",
    short_description: "Passive and active biomonitoring of airborne toxic metals using urban epiphytic lichens and tree bark indicators.",
    full_description: "Urban vehicular density and brick kiln emissions disperse toxic fine particulate matter (PM2.5 / PM10) laden with toxic metals. This project uses biomonitors (Lichen species and tree bark) across Greater Dhaka to reconstruct spatial atmospheric deposition histories without requiring expensive continuous air sampling stations.",
    status: "archived",
    start_date: "2021-01-01",
    end_date: "2023-12-31",
    year: "2021 — 2023",
    funding_info: "JU Faculty Research Grant #JU-FRG-21",
    funding_org: "Jahangirnagar University",
    grant_amount: "BDT 850K ($7,200 USD)",
    research_question: "Can epiphytic biomonitors accurately delineate spatial deposition hotspots of lead and cadmium across mega-city atmospheric corridors?",
    objectives: [
      "Establish 40 biomonitoring sampling grids across urban and industrial transects.",
      "Quantify metal content via Atomic Absorption Spectroscopy (AAS).",
      "Correlate lichen metal burdens with traffic density and brick kiln proximities."
    ],
    methodology: "Tree bark and lichen collection → Microwave digestion → Flame/Graphite furnace AAS → Inverse Distance Weighting (IDW) air pollution interpolation.",
    study_area: "Greater Dhaka Metropolitan & Peri-Urban Kiln Clusters",
    study_area_description: "High-density urban zones and northern brick manufacturing corridors.",
    findings: "Demonstrated strong correlation (r = 0.84) between lichen lead concentrations and heavy vehicular congestion nodes.",
    outputs: "2 Journal Articles, Published Urban Air Heavy Metal Atlas.",
    hero_image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1600&q=85",
    image_alt: "Urban environmental air quality monitoring and particulate matter research",
    featured_image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1600&q=85",
    gallery: [],
    display_order: 6,
    is_featured: false,
    is_published: true,
    published_at: "2021-01-01T00:00:00Z",
    created_at: "2021-01-01T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
    research_areas: [SEED_RESEARCH_AREAS[1], SEED_RESEARCH_AREAS[3]],
    researchers: [SEED_RESEARCHERS[0], SEED_RESEARCHERS[4]],
    collaborators: [SEED_COLLABORATORS[0]],
    publications: []
  }
];
